---
- name: Ensure pre-checks runs successfully.
  shell: "/opt/bluedata/bundles/bluedata-prechecks-epic-entdoc-5.0.bin"
  changed_when: false
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "{{ res.stdout }}"
